### ISSUE TITLE
Xone

### ISSUE THREAD

**Issue by jiuyu1139** [hve-notes/site#41]
## 主题名称 / Theme Name
- Xone

## 介绍 / Introduction
- Xone是一款简洁Gridea主题博客
支持全站搜索功能
首页配置轮播置顶
内置Valine评论、社交链接
支持友链页面
持续更新不断完善

## 仓库地址 / Github Repo
- https://github.com/Z-LHL/gridea-theme-Xone

## 预览地址 / Preview Address
-http://zaqc95.coding-pages.com/

## 截图 / Screenshots
- https://p3.pstatp.com/origin/pgc-image/0fb644d50f5b4be29b15b1b7e5475e68

**Comment by EryouHao** [comment]
仓库地址有吗，否则无法上架呢，没地方去下载 😂
